language: erlang
otp_release:
- 17.3
script:
  - rebar get-deps
  - rebar compile
  - rebar -r eunit skip_deps=true
  - rebar -r ct
  - rebar generate
  - git status
after_script:
  - git status
before_deploy:
  - git status
  - "pwd"
  - "ls -al"
  - "ls apps/test_app"
  - "ls -al node"
  - "zip -r test_app_node.zip node/test_app"
  - "zip -r eunit.zip apps/test_app/.eunit"
  - "zip -r ct_logs.zip apps/test_app/logs"
  - "ls -al"
  - git status
deploy:
  provider: releases
  api_key:
    secure: c8XY7rNh3ntcnu5rojs3X2snFxONtbr5cQ3RAmLKZ/fmoyoCyVctt90tmqpwj3WEeQ/7wlrinxD7TwQiMDfzXV5FIcR4bmiG1/0C65EbXB0nwm3Vu7vb+J4EtnYuq1y5Yqm7L/CxuKrzEJQz5tormW5LBqbRff7Gzg+5P4+u8fA=
  file:
    - "/home/travis/build/dbost/test_app/eunit.zip"
    - "/home/travis/build/dbost/test_app/ct_logs.zip"
    - "/home/travis/build/dbost/test_app/test_app_node.zip"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_success:
  - git status